pubAuthor: ryanwang
pubAUthorEmail: i@ryanc.cc
pubDescription: 1Panel REST API client for Dart
pubHomepage: https://github.com/1Panel-dev/1Panel
pubLibrary: cn.1panel
pubName: one_panel_client
pubVersion: 1.0.0
